services:
  - type: web
    name: api-order-cafe
    env: php
    region: oregon
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader && php artisan migrate --force"
    startCommand: "vendor/bin/heroku-php-apache2 public/"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_MINI_APP_URL
        value: https://t.me/ahseven_bot
